---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_RANGE_HOME: "192.168.11.55-192.168.11.60"
  METALLB_POOL_HOME: "homepool"
  OPENOBSERVE_LB_IP: "192.168.11.55"
  FIREFLY_LB_IP: "192.168.11.56"
  CHANGEDETECTION_LB_IP: "192.168.11.57"
