apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:VbUuU5eUjvtxN+cGDOGucj5fMrc=,iv:FEsjyf03RqHag8NLXrBhOlha2RSBBhSyrVG0fYeHQrk=,tag:o3D/GrZMhFvjgHhfHsIrlg==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:gy5+eQX7CIO0/G4pvVA=,iv:WnDiB4WALXW1LQmoj//QgvZMFzhBenEnHY7sbKg+9Mo=,tag:yI7AVUuG7X/jGoIqltfwDg==,type:str]
    NAS_PATH_IMMICH: ENC[AES256_GCM,data:ZpiDyONcyZu+tK27FfhHU3Ojz1fH+ekp,iv:u8cmQA/Jm7zjyNTGTjx6wlofHvKoINN5EPaCrv7VKaI=,tag:MIW//q3YVZS0NENrICnNnw==,type:str]
    LETSENCRYPT_EMAIL: ENC[AES256_GCM,data:MMMyFFMK552ydf0Uoitc6tS2CTI=,iv:Gw3y5YpjYevoo3mQK9bqH7tk9C02Io1pVjnDZ7f/oLI=,tag:JR0CCewLwPLfHvRuVoRVCQ==,type:str]
    CLUSTER_DOMAIN: ENC[AES256_GCM,data:Y+jLWqjEAZRamx0rrKkf3vE=,iv:m/HT7+e5j+jTXZAK71CfCDxRbUC+kRN1EXYqX6Eb+Xk=,tag:w/nJZ0/HYsX9+yhVqv6Zjw==,type:str]
sops:
    age:
        - recipient: age1gn9vptm6up8yepw4k2wugpa5wjenmuxejh6ulkww0pkh4c6r24tqajsspe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveUlrYWNKaUFnV3I3NGpU
            aU9lSjRxZ01CcmFXWGdTRmpIVk5zV3RUOVdrClNNQzBFekdOa0QvdjN5OENyZlRK
            MFo3aHlFNHBkVVpnb1JadjlCQS9PeEUKLS0tIDNhdklocDVVWFF3TEZBQlljVXFw
            aG1KVndEeC9lazRmWGg5Z0lmejBXeHMKUtuELq+3K3FJTW6Arp/WgrbuJehegtc0
            eU35eDmwy/8/s3VKsy+go0/bHUD+xxMscNVv5P12sa05DzHD9yiulg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T00:00:55Z"
    mac: ENC[AES256_GCM,data:AStwv3vkQ/0JjuLbwUMsNeAA7PhBAr6W+FkgdbGi3VoeUlGPohOtrLryiz5YxJtpAWCYI1kzwHJE5jvmQPdHzRFEI3exkd+09Xc+YfNe9jdnj4VMhKaGEaZzwXt8xujJwFSy2Qz42AjxLym/Yx9r1/yC75Ll/wkEfjkqhOH8MUA=,iv:FrXLOQauAS4P5mw/a4XVZJM6PKMzcgFUTSGpZc7APv4=,tag:hQ+4sMkgroQbUdXuAFhpow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
