apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    ZO_ROOT_USER_EMAIL: ENC[AES256_GCM,data:VbUuU5eUjvtxN+cGDOGucj5fMrc=,iv:FEsjyf03RqHag8NLXrBhOlha2RSBBhSyrVG0fYeHQrk=,tag:o3D/GrZMhFvjgHhfHsIrlg==,type:str]
    ZO_ROOT_USER_PASSWORD: ENC[AES256_GCM,data:gy5+eQX7CIO0/G4pvVA=,iv:WnDiB4WALXW1LQmoj//QgvZMFzhBenEnHY7sbKg+9Mo=,tag:yI7AVUuG7X/jGoIqltfwDg==,type:str]
sops:
    age:
        - recipient: age1gn9vptm6up8yepw4k2wugpa5wjenmuxejh6ulkww0pkh4c6r24tqajsspe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveUlrYWNKaUFnV3I3NGpU
            aU9lSjRxZ01CcmFXWGdTRmpIVk5zV3RUOVdrClNNQzBFekdOa0QvdjN5OENyZlRK
            MFo3aHlFNHBkVVpnb1JadjlCQS9PeEUKLS0tIDNhdklocDVVWFF3TEZBQlljVXFw
            aG1KVndEeC9lazRmWGg5Z0lmejBXeHMKUtuELq+3K3FJTW6Arp/WgrbuJehegtc0
            eU35eDmwy/8/s3VKsy+go0/bHUD+xxMscNVv5P12sa05DzHD9yiulg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T22:34:31Z"
    mac: ENC[AES256_GCM,data:HmLaB6FfYUp1XnKAoG5mCgwCEFYKoDuQBasazbV6oqJmTzwZbZRaRO8DG04bbb7OvDAsBL0e3F5m93wtiqRYyCNByk3NFGASewADvoEhaA75izV00QKtnf/nqnKbytyfkiUdDvHBGWobMUj9z8wR9cFv2/g+WB80quHsg9hDOLM=,iv:hBjPKvwKAYCdhQQk1kvTGoYPGt1CduMdDojj2A8GKDg=,tag:AZrJ1tUr8RHNYkkwmuVZfw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
