---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openobserve
  namespace: network
spec:
  interval: 5m
  chart:
    spec:
      chart: openobserve
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: openobserve
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    config:
      ZO_ROOT_USER_EMAIL: "${ZO_ROOT_USER_EMAIL}"
      ZO_ROOT_USER_PASSWORD: "${ZO_ROOT_USER_PASSWORD}"
    postgres:
      enabled: false
    persistence:
      enabled: true
      size: 10Gi
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: "${METALLB_POOL_HOME}"
        metallb.universe.tf/loadBalancerIPs: "${OPENOBSERVE_LB_IP}"
