---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: firefly-iii-stack
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: firefly-iii-helm
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              name: firefly-iii
            patch: |
              - op: replace
                path: /spec/type
                value: LoadBalancer
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1address-pool
                value: "${METALLB_POOL_HOME}"
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
                value: "${FIREFLY_LB_IP}"
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1allow-shared-ip
                value: firefly-shared
          - target:
              kind: Service
              name: firefly-iii-importer
            patch: |
              - op: replace
                path: /spec/type
                value: LoadBalancer
              - op: replace
                path: /spec/ports/0/port
                value: 8080
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1address-pool
                value: "${METALLB_POOL_HOME}"
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
                value: "${FIREFLY_LB_IP}"
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1allow-shared-ip
                value: firefly-shared
  values:
    firefly-db:
      enabled: true
      storage:
        existingClaim: firefly-iii-firefly-db-storage-claim
      backup:
        destination: ""
      configs:
        DBNAME: firefly
        DBUSER: firefly
        POSTGRES_USER: firefly

    firefly-iii:
      enabled: true
      image:
        # renovate: depName=fireflyiii/core datasource=docker
        tag: "version-6.5.6@sha256:de3224a309c9a6ef3fe9c6078b6ed8a0fb8725b5b805d672ed8da40d7b24826e"
      config:
        existingSecret: firefly-iii-secrets

    importer:
      enabled: true
      image:
        # renovate: depName=fireflyiii/data-importer datasource=docker
        tag: "version-2.2.2@sha256:7cfbd579a13ebd4d5183bf8d2c7d835262e6f412a4d24db7f3c2ad1db427edbb"
      fireflyiii:
        url: "http://firefly-iii"
      config:
        existingSecret: firefly-iii-secrets
