---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: firefly-iii-stack
      version: 0.9.1
      sourceRef:
        kind: HelmRepository
        name: firefly-iii-helm
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
              name: firefly-iii
            patch: |
              - op: replace
                path: /spec/type
                value: LoadBalancer
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1address-pool
                value: "${METALLB_POOL_HOME}"
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
                value: "${FIREFLY_LB_IP}"
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1allow-shared-ip
                value: firefly-shared
          - target:
              kind: Service
              name: firefly-iii-importer
            patch: |
              - op: replace
                path: /spec/type
                value: LoadBalancer
              - op: replace
                path: /spec/ports/0/port
                value: 8080
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1address-pool
                value: "${METALLB_POOL_HOME}"
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
                value: "${FIREFLY_LB_IP}"
              - op: add
                path: /metadata/annotations/metallb.universe.tf~1allow-shared-ip
                value: firefly-shared
  values:
    firefly-db:
      enabled: true
      storage:
        existingClaim: firefly-iii-firefly-db-storage-claim
      backup:
        destination: ""
      configs:
        DBNAME: firefly
        DBUSER: firefly
        POSTGRES_USER: firefly

    firefly-iii:
      enabled: true
      image:
        # renovate: depName=fireflyiii/core datasource=docker
        tag: "version-6.5.9@sha256:fe4ecec4c2ba2b2978a32b3defaf270407f9fddf0e789a18648121ab84bb68d2"
      config:
        existingSecret: firefly-iii-secrets

    importer:
      enabled: true
      image:
        # renovate: depName=fireflyiii/data-importer datasource=docker
        tag: "version-2.0.0@sha256:725ac2909fc02960cfbc7d866ea7dd576459407701d65f294911104bcd819cd2"
      fireflyiii:
        url: "http://firefly-iii"
      config:
        existingSecret: firefly-iii-secrets
