---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefly-iii
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: firefly-iii
      version: 1.9.12
      sourceRef:
        kind: HelmRepository
        name: firefly-iii-helm
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    config:
      existingSecret: firefly-iii-secrets

    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: "${METALLB_POOL_HOME}"
        metallb.universe.tf/loadBalancerIPs: "${FIREFLY_LB_IP}"

    persistence:
      storageClassName: longhorn
      storage: 2Gi

    firefly-db:
      enabled: true
      global:
        postgresql:
          auth:
            existingSecret: firefly-iii-secrets
            secretKeys:
              userPasswordKey: DB_PASSWORD
              adminPasswordKey: DB_PASSWORD
