---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-firefly-db-storage-claim
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
