apiVersion: v1
kind: Secret
metadata:
    name: firefly-iii-secrets
    namespace: home
stringData:
    APP_KEY: ENC[AES256_GCM,data:s8Ju+N4a9AyoKU7dI2asLLXSC66OAg5EXBFqRTnY1vw=,iv:aBv9Ik58gMPIff/Hr0ts2jqZvIwIDRV6J+g2KTeiRck=,tag:FMORiF0BKal4vJ3RKYJMxQ==,type:str]
    APP_URL: ENC[AES256_GCM,data:I6mxg1DpgBN7PkVpA7+aH87nFwA=,iv:/LVrKqAt/Os62GY4IM3Mj+vE1cuFq/F+DnafyDcLSmk=,tag:GH6ZjkMpdXSYKPTfafwm+g==,type:str]
    TRUSTED_PROXIES: ENC[AES256_GCM,data:sOY=,iv:qBRhVvWrk6RJEZ+otYF8eomFnCGowW9dDIOb7fzXlQw=,tag:HU/7TT5SmoHjyR5oPCUaGw==,type:str]
    DB_CONNECTION: ENC[AES256_GCM,data:wyZrc+0=,iv:AGarTu0ojJoIS1n7uaxb0CyGY9DODfphO+rvFFNZR/U=,tag:mqyNHp+35dMaXcQYMG2jyA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:tgaIH2XyUh5pUx+So9kFz91xAaXvajrnjGZ8g5Trf1Ps,iv:6wEIK5t9DDFoHLwARinbKrRdygzJ09krgwfnTb7EvE0=,tag:oL7j64OAEbh2cQrzYm8KCA==,type:str]
    DB_PORT: ENC[AES256_GCM,data:pOpA9Q==,iv:V26VasAxTDDefk1Majw6A0NlJtICU6YFbwkdgeUTzpM=,tag:+Nu0l1Xukl5C2zydzK/zJA==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:/DGUsMR5WdIezg==,iv:blLt2UJEuv9qVU9mqc7qB2NNX4SfP3+TK89NB1vKpPk=,tag:fUaI4vGxdvis/cOa/QUH7Q==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:W077O4ivzHj6TQ==,iv:mQTHL+azlKq19UMTmSkls/ds7DQukOP9PbVSv2qd2BA=,tag:zID17ntesLoRaK3JfGF10Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:9wCyBsmjtJl1Su0Vjxo=,iv:AHtiwyai2Fd4RM+5Wb7eReF3iFR+NoYiubZ0xt8TVEg=,tag:Y3RRqV2hYE5aMdvsNJN0Yg==,type:str]
sops:
    age:
        - recipient: age1gn9vptm6up8yepw4k2wugpa5wjenmuxejh6ulkww0pkh4c6r24tqajsspe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZzRWa0NUMVRyM3hsQnEr
            RnRrcFVYOFBmQjBwRTlncjdqTit0TXRjclVRCk1IS0t6aHNpQW5OTk9KUnVkbFUw
            R0dIdG5ndGdtMWJHdnFUNGpjN3d5S3cKLS0tIERPQzJ6d3ZSdjR2UmM3VHlEdmZm
            ZDRnNlJHbmR2UFNOQVRoWDRpUjFQM0EKwwTfgrokigRwXpvykPbzgANyywbFmpDd
            lEewKOhuM7aQ1gKpQKcYhuhe7v34KI5BGxO/HtUlsMWAiGRxfnxMXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T16:36:28Z"
    mac: ENC[AES256_GCM,data:0AgE+ZHIrbUPyIcqG2w+fc/BGcu3x/nYJnfdtwEZXX1B/auzF9DAGg1P75zQFQ+4eBNucajqIqA8FMvz6BvH+CpcLyIEi/By61I4vDvnbMDu/4Kh7qDZo1/R+JKXa9S6qUf+9t/tfs5+CuxgA2Hb0anvOgbGTwxsatgTcWK5R4w=,iv:YHoUYdUK3eKJ3p3wz+4/x+4jw0fPU1Aa3e/Y8yaClqI=,tag:0lCm7+9Z766BQm5xD7c0Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
