---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - pv-nfs.yaml
  - pvc-photos.yaml
  - pvc-model-cache.yaml
  - postgres-cluster.yaml
  - helm-release.yaml
