---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: home
spec:
  instances: 1

  storage:
    size: 10Gi
    storageClass: longhorn

  # renovate: depName=ghcr.io/tensorchord/cloudnative-vectorchord datasource=docker
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-secrets
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;

  enableSuperuserAccess: false

  affinity:
    nodeSelector:
      node.homelab/cpu-tier: high

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
