---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-photos-nfs
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - hard
    - nfsvers=4.1
    - noatime
    - rsize=131072
    - wsize=131072
  nfs:
    server: "${NAS_SERVER}"
    path: "${NAS_PATH_IMMICH}"
  claimRef:
    name: immich-photos
    namespace: home
