---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: immich-photos-nfs
  resources:
    requests:
      storage: 2Ti
