---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-model-cache
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 30Gi
