apiVersion: v1
kind: Secret
metadata:
    name: immich-secrets
    namespace: home
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:Yv3bEa/z+VyWYx7Yaj0=,iv:AMrdb0o8qDw6czdG2StEumWl5xdPu7s2Ry6CpJ3RiVc=,tag:ynAYU+3oYM3rUhfou6pBfQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:ti+5zZDU,iv:It+eywnA/XQGgGcIRWYfZ+ZwErh0sx1E2+5KmZOCgJE=,tag:4w4yylNIxnz8h4plxTr8iA==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:6OFsPVwK,iv:D6kqLU/amts8ZYpnXeaDzwYuZRHNK87UkQfsJ4NXb1s=,tag:C6kRsHCP+u0AO5Q8hM/qJg==,type:str]
sops:
    age:
        - recipient: age1gn9vptm6up8yepw4k2wugpa5wjenmuxejh6ulkww0pkh4c6r24tqajsspe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cEYvbzR2NmM5SVhheExq
            eGdYU1ZNaHdPSzhSS0NIV3Q5b3pzY3dmcVhzCkhZSlZ2YXBBQ25ZZUNsVkl2MGdy
            REhWRFFyb3QzbkF4dWYxSlVmMHZ5ZHMKLS0tIGpHek1kK0RpZ2ZmU3lVVFpvWGZp
            SmhGbldjL0tPWkQ1V0Iyc2tTZFpjVHMKtKNZIU7rpPYhxe6s+wcgSTUl9Kp7g+uO
            Hrfcu4zw/7vN6TIUbIDSqhwK4D3FuqRb2fAFZvQybF0c9kwvfMlgtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T01:29:39Z"
    mac: ENC[AES256_GCM,data:5hQjHnOzfWlgcmtGWQpXC98pGTHWANiUZWWnr5fXwEdptn5lZtP89I8ndSDa60svgxyRxCRnaSxQY/UIAOmjD33feACKhzn/zv+n+K2wkx8V063XdrBlqDR0lL+qk5C1P4NltcCIkaAtYuy2UJ5TeHsPt7Jt9gFRZ/8EQBwAHQY=,iv:1Wc8L+So2+E6MFLtY+F41p/kTItxEZ0MHMpG321mUqo=,tag:pn+L4zewQ16Oh8+QTUzdtg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
