---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pve-tls
  namespace: network
spec:
  secretName: pve-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - pve.${CLUSTER_DOMAIN}
  ipAddresses:
    - ${PVE_IP}
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: truenas-tls
  namespace: network
spec:
  secretName: truenas-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - truenas.${CLUSTER_DOMAIN}
  ipAddresses:
    - ${NAS_SERVER}
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portainer-tls
  namespace: network
spec:
  secretName: portainer-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - portainer.${CLUSTER_DOMAIN}
  ipAddresses:
    - ${DOCKER_HOST_IP}
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opnsense-tls
  namespace: network
spec:
  secretName: opnsense-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - opnsense.${CLUSTER_DOMAIN}
  ipAddresses:
    - ${OPNSENSE_IP}
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-tls
  namespace: network
spec:
  secretName: unifi-tls
  duration: 8760h
  renewBefore: 720h
  dnsNames:
    - unifi.${CLUSTER_DOMAIN}
  ipAddresses:
    - ${UNIFI_IP}
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
