---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      annotations:
        metallb.universe.tf/address-pool: "${METALLB_POOL_HOME}"
        metallb.universe.tf/loadBalancerIPs: "${TRAEFIK_LB_IP}"
    providers:
      kubernetesCRD:
        # Necesario para que IngressRoutes en namespace `network` referencien
        # ServersTransport y servicios de otros namespaces (home, tools, network)
        allowCrossNamespace: true
      kubernetesIngress:
        allowCrossNamespace: true
